### ISSUE TITLE
return types of methods

### ISSUE THREAD

**Issue by perludum** [felixSchl/photoshop.d.ts#7]
Currently all methods in the /dist declarations are of type void, though many methods actually have return values.

There seems to be a little bug in parsers/types.ts lines 225-267 where the "name" of the return type of methods somehow gets mapped twice into objects like ` {"name":{"name":"string","range":null}}`

Workaround: Changing `method.returns.name` to `method.returns.name.name` in line 60 of renderers/types.ts produces correct declarations files with return types, but does not fix the bug at its root.

**Comment by felixSchl** [comment]
Good find. Do you have any idea how to fix the bug? I would welcome a PR either with a fix or with that workaround provided it doesn't break anything else

**Comment by perludum** [comment]
OK I'll prepare it!

**Comment by perludum** [comment]
done in https://github.com/felixSchl/photoshop.d.ts/pull/10
