### ISSUE TITLE
rename ps.d.ts to index.d.ts

### ISSUE THREAD

**Issue by perludum** [felixSchl/photoshop.d.ts#8]
I’d like to propose renaming the files named "ps.d.ts" to "index.d.ts" to get them automatically recognized when adding `"types": ["photoshop.d.ts/dist/cc/"]` to the tsconfig.json.

No need to add a reference path in each file any more and Intellisense gets activated in VSCode too.

**Comment by felixSchl** [comment]
That  sounds like a great idea, do u mind submitting a PR? app.ts would need updating and the root ps.d.ts file too

**Comment by perludum** [comment]
done in https://github.com/felixSchl/photoshop.d.ts/pull/9/commits/6928cca64475eea5b04a15c8793a219042ee9d5a
